# Generated by Django 6.0.4 on 2026-05-30 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weekly', '0001_hr_demo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('prox_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sage_pay_ref', models.PositiveIntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('clock_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('group', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(blank=True, db_index=True, max_length=64)),
                ('contract_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('basic_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('holidays_left', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sage_pay_freq', models.CharField(blank=True, max_length=64)),
                ('sage_paylink', models.CharField(blank=True, max_length=128)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('shift_group', models.CharField(blank=True, max_length=128)),
                ('ot_rule', models.CharField(blank=True, max_length=128)),
                ('default_activity', models.CharField(blank=True, max_length=128)),
                ('default_job', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='weekly_empl_full_na_69faaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('holiday_form', 'Holiday form'), ('correspondence', 'Correspondence'), ('other', 'Other')], default='other', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='employee_documents/%Y/%m/')),
                ('s3_key', models.CharField(blank=True, max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='weekly.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_employee_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
